spring.application.name=Heritage
server.port=9888
spring.jpa.database=POSTGRESQL
spring.sql.init.platform=postgres

spring.datasource.url=jdbc:postgresql://localhost:5432/heritage_db
spring.datasource.username=postgres
spring.datasource.password=snptlapp

spring.datasource.class.for.name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update